### ISSUE TITLE
Symbiote preview does not work properly during combat

### ISSUE THREAD

**Issue by Tempus** [Tempus/Disciple-Monster-Train#226]

**Comment by RisingDusk** [comment]
Fixed in 661624a.

Note that the combat preview has problems with spawn point changes that neither Chrono or I can explain right now. The particular solution we went with to this was to turn off dynamic adjustment of Symbiote's stats during the combat phase. This may necessitate balance adjustments later and removes a few "neat" interactions with things like Gravity, but at least stabilizes the utterly broken combat preview (which is a bad problem). We may revisit this later.
